# Generated by Django 3.0.2 on 2020-01-12 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=150)),
                ('start', models.CharField(max_length=200)),
                ('destination', models.CharField(max_length=200)),
                ('mode_of_travel', models.CharField(max_length=50)),
                ('distance', models.IntegerField()),
                ('carbon_footprint', models.IntegerField()),
                ('roundtrip', models.BooleanField(default=False)),
                ('favorites', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
