# Generated by Django 3.0.2 on 2020-01-12 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='carbon_footprint',
            field=models.FloatField(),
        ),
    ]
