# Generated by Django 3.0.2 on 2020-01-12 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0004_remove_trip_favorites'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='number_of_trips_in_a_week',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
