# Generated by Django 3.0.2 on 2020-01-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trips', '0005_trip_number_of_trips_in_a_week'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='distance',
            field=models.FloatField(),
        ),
    ]
